version: "3"  
services:
  proy_nginx:
    container_name: "proy_nginx_prod"
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx-prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/certs:/etc/certs/
      - ./frontend-react/dist/:/usr/share/nginx/html/
    depends_on:
      - proy_react
      - proy_laravel

  proy_react:
    container_name: "proy_react_prod"
    image: node:18-alpine
    restart: unless-stopped
    volumes:
      - ./frontend-react/:/home/node/app/
      - ./config/buildnode.sh:/buildnode.sh:ro
    working_dir: /home/node/app/
    command: sh /buildnode.sh
    environment:
      - FAST_REFRESH=false

  proy_laravel:
    container_name: "proy_laravel_prod"
    working_dir: /app/
    image: bitnami/laravel
    restart: unless-stopped
    volumes:
      - ./backend--Laravel:/app/
      - ./config/startlaravel-prod.sh:/startlaravel-prod.sh:ro
    depends_on:
      - proy_db
    env_file:
      - ./backend--Laravel/.env-prod
    command: /bin/sh /startlaravel-prod.sh

  proy_db:
    container_name: "proy_db_prod"
    image: mariadb
    restart: unless-stopped
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_USER=proy_user
      - MARIADB_PASSWORD=proy_user
      - MARIADB_DATABASE=proy

